version: "3"
services:
  api:
    build:
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CLIENT_HOST=http://localhost:3000
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - API_HOST=http://api:5000
    ports:
      - "3000:3000"
